version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: atul_pandey
      POSTGRES_PASSWORD: atul123
      POSTGRES_DB: atul_pandey
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atul_pandey"]
      interval: 5s
      retries: 5
      timeout: 3s

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/src/.env  # Load environment variables for backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001" # Expose the backend service on port 3001
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3001/health || exit 1"]
      interval: 5s
      retries: 5
      timeout: 3s
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80" # Expose the frontend service on port 3000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/ || exit 1"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:
