name: Terraform CI/CD

on:
  push:
    branches:
      - kra-atul  # Runs automatically when code is pushed to kra-atul branch

  workflow_dispatch:
    inputs:
      command:
        description: "Terraform Command to Run"
        required: true
        default: "plan"
        type: choice
        options:
          - fmt
          - validate
          - plan

permissions:
  id-token: write  # Needed for OIDC authentication
  contents: read   # Allows reading repo contents

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::590184134827:role/atul-oidc
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform_code

      - name: Determine Terraform Command
        run: |
          if [[ -z "${{ github.event.inputs.command }}" ]]; then
            echo "Running automatic Terraform Plan..."
            terraform fmt -check
            terraform validate
            terraform plan -out=tfplan
          else
            echo "Running selected Terraform command: ${{ github.event.inputs.command }}"
            terraform ${{ github.event.inputs.command }}
          fi
        working-directory: terraform_code
