name: Terraform CI/CD

on:

  push:
    branches:
      - kra-atul  # Runs on push to kra-atul branch   

  workflow_dispatch:
    inputs:
      command:
        description: "Terraform Command to run"
        required: true
        default: "plan"
        type: choice
        options:
          - init
          - fmt
          - validate
          - plan
          - apply
          - destroy

permissions:
  id-token: write  # Needed for OIDC authentication
  contents: read   # Allows reading repo contents

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::590184134827:role/atul-oidc
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform_code

      - name: Run Terraform Command
        run: |
          echo "Running Terraform command: ${{ github.event.inputs.command }}"
          terraform ${{ github.event.inputs.command }}
        working-directory: terraform_code
