name: Terraform CI/CD

on:
  push:
    branches:
      - kra-atul  # Runs on push to kra-atul branch  

  workflow_dispatch:
    inputs:
      command:
        description: "Terraform Command to run"
        required: true
        default: "plan"
        type: choice
        options:
          - init
          - fmt
          - validate
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Debug: List Directory After Checkout
        run: |
          echo "Current Directory Structure:"
          ls -R          

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::590184134827:role/atul-oidc
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug: Confirm terraform_code Exists
        run: |
          if [ ! -d "terraform_code" ]; then
            echo "Error: terraform_code directory is missing!"
            exit 1
          fi

      - name: Initialize Terraform
        run: |
          cd terraform_code
          terraform init || { echo "Terraform init failed"; exit 1; }
          ls -alh .terraform || echo "No .terraform directory created!"
        working-directory: terraform_code

      - name: Check Directory Structure
        run: |
          echo "Listing contents of terraform_code"
          ls -R terraform_code
        working-directory: terraform_code

      - name: Verify Terraform Providers
        run: |
          echo "Checking .terraform directory"
          if [ -d ".terraform" ]; then
            ls -R .terraform
          else
            echo "Error: .terraform directory not found!"
            exit 1
          fi
        working-directory: terraform_code

      - name: Run Terraform Command
        run: |
          echo "Running Terraform command: ${{ github.event.inputs.command }}"
          terraform ${{ github.event.inputs.command }}
        working-directory: terraform_code

